[build]
  base = "web"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://api.latitude-ventas.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
